=== hyperpc/CSharp_XML/ch07_ADONET/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xsd:simpleType name="NotesType">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="500"></xsd:maxLength>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="NameType">
        <xsd:restriction base="xsd:string">
            <xsd:minLength value="3"></xsd:minLength>
            <xsd:maxLength value="255"></xsd:maxLength>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="BalanceType">
        <xsd:restriction base="xsd:decimal">
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:simpleType name="CountryType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="china"></xsd:enumeration>
            <xsd:enumeration value="usa"></xsd:enumeration>
            <xsd:enumeration value="england"></xsd:enumeration>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:element name="homephone" type="xsd:string" substitutionGroup="handphone"></xsd:element>
    <xsd:element name="handphone" type="xsd:string"></xsd:element>
    <xsd:complexType name="CustomerType">
        <xsd:all>
            <xsd:element name="firstname" type="NameType"></xsd:element>
            <xsd:element name="lastname" type="NameType"></xsd:element>
            <xsd:element name="balance" type="BalanceType"></xsd:element>
            <xsd:element  name="country" type="CountryType" fixed="china"></xsd:element>
            <xsd:element ref="homephone" ></xsd:element>
            <xsd:element name="notes" type="NotesType"></xsd:element>
        </xsd:all>
        <xsd:attribute name="id" type="xsd:int" use="required"></xsd:attribute>
    </xsd:complexType>
    <xsd:element name="customers">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="customer" type="CustomerType" minOccurs="0" maxOccurs="unbounded"></xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== hyperpc/CSharp_XML/ch05_XmlSchema/schema2.xml
<?xml version="1.0" encoding="UTF-8"?>
<customers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="schema.xsd">
    <customer id="1">
        <firstname>John</firstname>
        <lastname>Cranston</lastname>
        <balance>110.00</balance>
        <country>china</country>
        <homephone>(445) 269-9857</homephone>
        <notes>
            <![CDATA[He registed as our member since 1990. John has nice credity. He is a member of Custom International.]]>
        </notes>
    </customer>
    <customer id="2">
        <firstname>Annie</firstname>
        <lastname>Loskar</lastname>
        <balance>112.00</balance>
        <country>china</country>
        <handphone>12345678901</handphone>
        <notes>
            <![CDATA[Annie registed as our member since 1984. She became our VIP customer in 1996.]]>
        </notes>
    </customer>
    <customer id="3">
        <firstname>Annie</firstname>
        <lastname>Christo</lastname>
        <balance>113.00</balance>
        <country>china</country>
        <handphone>12345678902</handphone>
        <notes>
            <![CDATA[Bernie registed as our member since 2010. He is a new member.]]>
        </notes>
    </customer>
    <customer id="4">
        <firstname>Ernestine</firstname>
        <lastname>Borrison</lastname>
        <balance>114.00</balance>
        <country>china</country>
        <homephone>(445) 269-7742</homephone>
        <notes>
            <![CDATA[Ernestine registed as our member since 2010. She is a new member.]]>
        </notes>
    </customer>
</customers>
