=== hyperpc/CSharp_XML/ch05_XmlSchema/schema.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT customers (customer*)>
<!ELEMENT customer (firstname, lastname, balance, country, homephone, notes)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT balance (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT homephone (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
<!ATTLIST customer id CDATA #REQUIRED>

=== hyperpc/CSharp_XML/ch06_ReaderWriter/XmlReaderWriterDemo/App_Data/schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
<!DOCTYPE customers SYSTEM "schema.dtd">
-->
<!DOCTYPE customers[
<!ELEMENT customers (customer*)>
<!ELEMENT customer (firstname, lastname, balance, country, homephone, notes)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT balance (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT homephone (#PCDATA)>
<!ELEMENT notes (#PCDATA)>
<!ATTLIST customer id CDATA #REQUIRED>
]>
<customers>
    <customer id="1">
        <firstname>John</firstname>
        <lastname>Cranston</lastname>
        <balance>110.00</balance>
        <country>china</country>
        <homephone>(445) 269-9857</homephone>
        <notes>
            <![CDATA[He registed as our member since 1990. John has nice credity. He is a member of Custom International.]]>
        </notes>
    </customer>
    <customer id="2">
        <firstname>Annie</firstname>
        <lastname>Loskar</lastname>
        <balance>112.00</balance>
        <country>china</country>
        <homephone>12345678901</homephone>
        <notes>
            <![CDATA[Annie registed as our member since 1984. She became our VIP customer in 1996.]]>
        </notes>
    </customer>
    <customer id="3">
        <firstname>Annie</firstname>
        <lastname>Christo</lastname>
        <balance>113.00</balance>
        <country>china</country>
        <homephone>12345678902</homephone>
        <notes>
            <![CDATA[Bernie registed as our member since 2010. He is a new member.]]>
        </notes>
    </customer>
    <customer id="4">
        <firstname>Ernestine</firstname>
        <lastname>Borrison</lastname>
        <balance>114.00</balance>
        <country>china</country>
        <homephone>(445) 269-7742</homephone>
        <notes>
            <![CDATA[Ernestine registed as our member since 2010. She is a new member.]]>
        </notes>
    </customer>
</customers>
