=== hyperpc/CSharp_XML/ch05_XmlSchema/SchemaObjectModel/App_Data/Customers.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="customers">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" name="customer">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="firstname">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="3" />
                                        <xs:maxLength value="255" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="lastname">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="3" />
                                        <xs:maxLength value="255" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="balance">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="0" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="country">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string" />
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="homephone">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="25" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="notes">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="500" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hyperpc/CSharp_XML/ch07_ADONET/ADONETDemo/App_Data/schema3.xml
<?xml version="1.0" encoding="utf-8"?>
<customers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="Customers.xsd">
    <customer id="6">
        <firstname>Young</firstname>
        <lastname>Bob2</lastname>
        <balance>200.06</balance>
        <country>china</country>
        <homephone>12345678903</homephone>
        <notes>&lt;![CDATA[This file can pass 6 validation.]]&gt;</notes>
    </customer>
    <customer id="7">
        <firstname>Young</firstname>
        <lastname>Bob3</lastname>
        <balance>200.07</balance>
        <country>china</country>
        <homephone>12345678904</homephone>
        <notes><![CDATA[This file can pass 7 validation.]]></notes>
    </customer>
</customers>
